### ISSUE TITLE
没有input组件吗???

### ISSUE THREAD

**Issue by dengshenkk** [MPComponent/mpvue-weui#24]
没有input组件吗??? 另外什么时候才可以全局引入啊? 每个地方都要引入有点麻烦.

**Comment by KuangPF** [comment]
`input ` 组件暂时不支持，由于 `mpvue` 不支持全局组件引入，因此目前来说也没有比较好的方法来支持全局引入。

**Comment by KuangPF** [comment]
下个版本支持。

**Comment by SunnyAdmin** [comment]
现在的searchBar组件。当isFocus设置为false时。搜索输入每一个字符都会自动退出一遍？

**Comment by KuangPF** [comment]
@SunnyAdmin 已修复 9e78b56e76c0107。
