### ISSUE TITLE
button组件-按钮文字无法渲染

### ISSUE THREAD

**Issue by rachelrrrr** [MPComponent/mpvue-weui#27]
按照文档的示例使用之后发现渲染结果button的文字没有了，看了一下源码button/index.vue 使用了slot，但mpvue貌似不支持slot...

mpvue-weui: `1.0.4`
mpvue: `1.0.18`

使用button组件：
![image](https://user-images.githubusercontent.com/17424977/50439528-58d45700-092d-11e9-841c-ea665fd610b3.png)

结果：
![image](https://user-images.githubusercontent.com/17424977/50439619-b1a3ef80-092d-11e9-8d7c-5c804ad6e556.png)

**Comment by KuangPF** [comment]
mpvue 对简单的 slot 是支持的,但诸如组件作为 slot ，scoped slot 等这种较为复杂的用法还无法支持 [issues 116](https://github.com/Meituan-Dianping/mpvue/issues/116)，你看你是不是将 button 放在了一个组件里面，或者可以参考一下 `/example` 下的例子。
