### ISSUE TITLE
好奇是否支持h5端,还有基础的组建应该怎么实现  现阶段我在用这个配和weui.css 希望也能够更新一下css这个

### ISSUE THREAD

**Issue by eachann1026** [MPComponent/mpvue-weui#29]
weui有个好处就是在其他端都可以正常使用,不用担心兼容性的问题

**Comment by KuangPF** [comment]
这个支持支持 h5 比较困难，因为里面很多组件都是基于小程序原生组件，然后只是进行了一定地分装。对于 h5 的支持 腾讯官方有 [weui web](https://github.com/Tencent/weui) 版本，可以参考下。
