### ISSUE TITLE
建议Uploader组件增加上传进度显示（可配置显示）

### ISSUE THREAD

**Issue by tangniyuqi** [MPComponent/mpvue-weui#31]

**Comment by KuangPF** [comment]
`uploader` 组件主要依赖 `wx.chooseImage` API，而`wx.chooseImage`没有提供类似上传进度的参数，因此暂时不考虑支持。

**Comment by tangniyuqi** [comment]
wx.chooseImage 不是上传，只是选择。。。
上传需要wx.upload，我意思是开放样式接口，在使用wx.upload的时候可以设置，我看weui的demo是有这个样式的，可能您这个项目没有整合进去。

对了，使用wx.upload上传后应该需要清理数据，目前没有看到api。。。

**Comment by KuangPF** [comment]
目前 `uploader` 只是调用了 `wx.chooseImage` API，返回的是本地临时文件路径列表，是没有调用`wx.uploadFile` 上传到实际的服务器上。
