### ISSUE TITLE
picker组件onConfirm返回值的index键名是inex？

### ISSUE THREAD

**Issue by styzy** [MPComponent/mpvue-weui#36]
![3Y@IC$1 `J`)A`HAW$A3(AN](https://user-images.githubusercontent.com/20041306/56873894-56634480-6a68-11e9-9660-f3e3ddbe799d.png)

![8(@T`OUZZR1P%4V7~T0}6CQ](https://user-images.githubusercontent.com/20041306/56873902-7135b900-6a68-11e9-806d-c2fd7b732009.png)

这个inex不会在下个版本改成index吧？

**Comment by KuangPF** [comment]
这个我修复下
