### ISSUE TITLE
toast 不会自动隐藏

### ISSUE THREAD

**Issue by Johnson-huang** [MPComponent/mpvue-weui#40]
<mp-toast v-model="showToast" content="content" :duration="1500"></mp-toast>

页面 created 时，this.showToast = true，但是不会自动隐藏，一直留在页面上，使用方法不对吗

**Comment by Johnson-huang** [comment]
<mp-toast v-model="showToast" content="content" :duration="1500"></mp-toast>

**Comment by Johnson-huang** [comment]
`<mp-toast v-model="showToast" content="content" :duration="1500"></mp-toast>`

**Comment by KuangPF** [comment]
在 `created` 生命周期中，`mp-toast` 还没有挂载完成，这时候你设置了 `showToast` 的值，因此在组件里面是监听不到 `showToast` 值的变化，代码如下：
https://github.com/MPComponent/mpvue-weui/blob/2b60f1a2e2ac8ebd4807d5e57f6b8ab10ffcbc70/src/toast/index.vue#L43-L50
你可以在 `mounted` 里面设置 
``` js
this.showToast = true
```
