### ISSUE TITLE
modal弹框不支持自定义body结构

### ISSUE THREAD

**Issue by duke-git** [MPComponent/mpvue-weui#54]
modal弹框不支持自定义body结构

**Comment by KuangPF** [comment]
`model` 组件 `content` 属性可自定义内容。

**Comment by duke-git** [comment]
content只能定义文字内容，要是定制html body结构呢

**Comment by KuangPF** [comment]
`model` 组件实质是调用的 [wx.showModal](https://developers.weixin.qq.com/miniprogram/dev/api/ui/interaction/wx.showModal.html),该 API 的 `content` 字段只支持 `string` 类型，因此 html body 结构不支持哈
